[build]
functions = "./functions"

[[redirects]]
from = "dummy/tmbd/*"
to = "/.netlify/functions/dummy/:splat"
status = 200
force = true

[[redirects]]
from = "/tmdb/*"
to = "/.netlify/functions/tmdb/:splat"
status = 200
force = true
