module.exports = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
      genre_ids: [16, 12, 35, 10751],
      id: 315162,
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      popularity: 2531.473,
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      release_date: '2023-01-04',
      title: 'Its dummy',
      video: false,
      vote_average: 8.4,
      vote_count: 4541,
    },
    {
      adult: false,
      backdrop_path: '/22z44LPkMyf5nyyXvv8qQLsbom.jpg',
      genre_ids: [27, 9648, 53],
      id: 631842,
      original_language: 'en',
      original_title: 'Knock at the Cabin',
      overview:
        'While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.',
      popularity: 2101.02,
      poster_path: '/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg',
      release_date: '2023-03-08',
      title: 'Knock at the Cabin',
      video: false,
      vote_average: 6.5,
      vote_count: 983,
    },
    {
      adult: false,
      backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
      genre_ids: [28, 12, 878],
      id: 505642,
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
      popularity: 2286.347,
      poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
      release_date: '2022-11-09',
      title: 'Black Panther: Wakanda Forever',
      video: false,
      vote_average: 7.3,
      vote_count: 4057,
    },
    {
      adult: false,
      backdrop_path: '/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg',
      genre_ids: [28, 12, 53],
      id: 646389,
      original_language: 'en',
      original_title: 'Plane',
      overview:
        'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.',
      popularity: 1579.028,
      poster_path: '/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg',
      release_date: '2023-03-15',
      title: 'Plane',
      video: false,
      vote_average: 6.9,
      vote_count: 873,
    },
    {
      adult: false,
      backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
      genre_ids: [878, 12, 28],
      id: 76600,
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      popularity: 1372.778,
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      release_date: '2022-12-14',
      title: 'Avatar: The Way of Water',
      video: false,
      vote_average: 7.7,
      vote_count: 5726,
    },
    {
      adult: false,
      backdrop_path: '/v2LilmCylr3bL9TCZSj6syjowZh.jpg',
      genre_ids: [35, 18],
      id: 937278,
      original_language: 'en',
      original_title: 'A Man Called Otto',
      overview:
        'When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.',
      popularity: 1123.571,
      poster_path: '/130H1gap9lFfiTF9iDrqNIkFvC9.jpg',
      release_date: '2023-03-29',
      title: 'A Man Called Otto',
      video: false,
      vote_average: 7.9,
      vote_count: 696,
    },
    {
      adult: false,
      backdrop_path: '/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg',
      genre_ids: [878, 27, 35],
      id: 536554,
      original_language: 'en',
      original_title: 'M3GAN',
      overview:
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      popularity: 1074.076,
      poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
      release_date: '2023-01-25',
      title: 'M3GAN',
      video: false,
      vote_average: 7.4,
      vote_count: 2024,
    },
    {
      adult: false,
      backdrop_path: '/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg',
      genre_ids: [18, 28],
      id: 677179,
      original_language: 'en',
      original_title: 'Creed III',
      overview:
        'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien - a fighter who has nothing to lose.',
      popularity: 1383.316,
      poster_path: '/vJU3rXSP9hwUuLeq8IpfsJShLOk.jpg',
      release_date: '2023-03-01',
      title: 'Creed III',
      video: false,
      vote_average: 7,
      vote_count: 319,
    },
    {
      adult: false,
      backdrop_path: '/gslT8t964rYXyqRcqrxFh77ikyb.jpg',
      genre_ids: [12, 878, 35],
      id: 640146,
      original_language: 'en',
      original_title: 'Ant-Man and the Wasp: Quantumania',
      overview:
        "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      popularity: 922.319,
      poster_path: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
      release_date: '2023-02-15',
      title: 'Ant-Man and the Wasp: Quantumania',
      video: false,
      vote_average: 6.4,
      vote_count: 996,
    },
    {
      adult: false,
      backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
      genre_ids: [28, 14, 878],
      id: 436270,
      original_language: 'en',
      original_title: 'Black Adam',
      overview:
        'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      popularity: 815.113,
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      release_date: '2022-10-19',
      title: 'Black Adam',
      video: false,
      vote_average: 7.1,
      vote_count: 4450,
    },
    {
      adult: false,
      backdrop_path: '/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg',
      genre_ids: [18],
      id: 785084,
      original_language: 'en',
      original_title: 'The Whale',
      overview:
        'A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.',
      popularity: 1394.175,
      poster_path: '/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg',
      release_date: '2023-03-01',
      title: 'The Whale',
      video: false,
      vote_average: 8.1,
      vote_count: 1110,
    },
    {
      adult: false,
      backdrop_path: '/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg',
      genre_ids: [28, 10749, 35],
      id: 758009,
      original_language: 'en',
      original_title: 'Shotgun Wedding',
      overview:
        'Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.',
      popularity: 928.204,
      poster_path: '/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg',
      release_date: '2023-03-29',
      title: 'Shotgun Wedding',
      video: false,
      vote_average: 6.3,
      vote_count: 646,
    },
    {
      adult: false,
      backdrop_path: '/qjGrUmKW78MCFG8PTLDBp67S27p.jpg',
      genre_ids: [16, 28, 12, 14, 53],
      id: 635302,
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      popularity: 687.032,
      poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
      release_date: '2021-01-27',
      title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
      video: false,
      vote_average: 8.3,
      vote_count: 2981,
    },
    {
      adult: false,
      backdrop_path: '/afsYFdid9pnnRd6tTrHFUbHgXJn.jpg',
      genre_ids: [878, 28, 12],
      id: 843794,
      original_language: 'ko',
      original_title: '정이',
      overview:
        'On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.',
      popularity: 621.337,
      poster_path: '/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg',
      release_date: '2023-01-20',
      title: 'JUNG_E',
      video: false,
      vote_average: 6.3,
      vote_count: 385,
    },
    {
      adult: false,
      backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
      genre_ids: [28, 12, 14, 878],
      id: 19995,
      original_language: 'en',
      original_title: 'Avatar',
      overview:
        'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
      popularity: 678.224,
      poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
      release_date: '2009-12-17',
      title: 'Avatar',
      video: false,
      vote_average: 7.6,
      vote_count: 28615,
    },
    {
      adult: false,
      backdrop_path: '/53BC9F2tpZnsGno2cLhzvGprDYS.jpg',
      genre_ids: [14, 28, 12, 53],
      id: 736526,
      original_language: 'no',
      original_title: 'Troll',
      overview:
        'Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?',
      popularity: 586.468,
      poster_path: '/9z4jRr43JdtU66P0iy8h18OyLql.jpg',
      release_date: '2022-12-01',
      title: 'Troll',
      video: false,
      vote_average: 6.7,
      vote_count: 1267,
    },
    {
      adult: false,
      backdrop_path: '/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg',
      genre_ids: [27, 9648, 53],
      id: 646385,
      original_language: 'en',
      original_title: 'Scream',
      overview:
        'Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.',
      popularity: 584.796,
      poster_path: '/fFE6E9jRKaiy7LHxk4jH1jIWzyT.jpg',
      release_date: '2022-02-17',
      title: 'Scream',
      video: false,
      vote_average: 6.7,
      vote_count: 2161,
    },
    {
      adult: false,
      backdrop_path: '/hJoe1i1MXoO7sXkbQRuONvUNPEo.jpg',
      genre_ids: [16, 12, 10751, 14],
      id: 502356,
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      popularity: 573.483,
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      release_date: '2023-04-26',
      title: 'The Super Mario Bros. Movie',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/94kQGMiFbs5MUTlt7kj9dewsMDi.jpg',
      genre_ids: [27, 53],
      id: 676547,
      original_language: 'en',
      original_title: 'Prey for the Devil',
      overview:
        'In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.',
      popularity: 494.395,
      poster_path: '/iCvgemXf2Kpr2LvpDmt5J9NhjKM.jpg',
      release_date: '2022-12-07',
      title: 'Prey for the Devil',
      video: false,
      vote_average: 7.2,
      vote_count: 550,
    },
    {
      adult: false,
      backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
      genre_ids: [14, 28, 35],
      id: 616037,
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview:
        'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
      popularity: 478.736,
      poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
      release_date: '2022-07-08',
      title: 'Thor: Love and Thunder',
      video: false,
      vote_average: 6.6,
      vote_count: 5557,
    },
  ],
  total_pages: 843,
  total_results: 16856,
};
